package com.cf.jkodiwrapper.types.list

enum class ListFieldsAll(var fieldName: String) {

    ALBUM("album"),
    ALBUMARTIST("albumartist"),
    ALBUMARTISTID("albumartistid"),
    ALBUMID("albumid"),
    ALBUMLABEL("albumlabel"),
    ALBUMRELEASETYPE("albumreleasetype"),
    ART("art"),
    ARTIST("artist"),
    ARTISTID("artistid"),
    CAST("cast"),
    CHANNEL("channel"),
    CHANNELNUMBER("channelnumber"),
    CHANNELTYPE("channeltype"),
    COMMENT("comment"),
    COMPILATION("compilation"),
    CONTRIBUTORS("contributors"),
    COUNTRY("country"),
    DATEADDED("dateadded"),
    DESCRIPTION("description"),
    DIRECTOR("director"),
    DISC("disc"),
    DISPLAYARTIST("displayartist"),
    DISPLAYCOMPOSER("displaycomposer"),
    DISPLAYCONDUCTOR("displayconductor"),
    DISPLAYLYRICIST("displaylyricist"),
    DISPLAYORCHESTRA("displayorchestra"),
    DURATION("duration"),
    ENDTIME("endtime"),
    EPISODE("episode"),
    EPISODEGUIDE("episodeguide"),
    FANART("fanart"),
    FILE("file"),
    FIRSTAIRED("firstaired"),
    GENRE("genre"),
    GENREID("genreid"),
    HIDDEN("hidden"),
    IMDBNUMBER("imdbnumber"),
    LASTPLAYED("lastplayed"),
    LOCKED("locked"),
    LYRICS("lyrics"),
    MOOD("mood"),
    MPAA("mpaa"),
    MUSICBRAINZALBUMARTISTID("musicbrainzalbumartistid"),
    MUSICBRAINZALBUMID("musicbrainzalbumid"),
    MUSICBRAINZARTISTID("musicbrainzartistid"),
    MUSICBRAINZTRACKID("musicbrainztrackid"),
    ORIGINALTITLE("originaltitle"),
    PLAYCOUNT("playcount"),
    PLOT("plot"),
    PLOTOUTLINE("plotoutline"),
    PREMIERED("premiered"),
    PRODUCTIONCODE("productioncode"),
    RATING("rating"),
    RELEASETYPE("releasetype"),
    RESUME("resume"),
    RUNTIME("runtime"),
    SEASON("season"),
    SET("set"),
    SETID("setid"),
    SHOWLINK("showlink"),
    SHOWTITLE("showtitle"),
    SORTTITLE("sorttitle"),
    SPECIALSORTEPISODE("specialsortepisode"),
    SPECIALSORTSEASON("specialsortseason"),
    STARTTIME("starttime"),
    STREAMDETAILS("streamdetails"),
    STUDIO("studio"),
    STYLE("style"),
    TAG("tag"),
    TAGLINE("tagline"),
    THEME("theme"),
    THUMBNAIL("thumbnail"),
    TITLE("title"),
    TOP250("top250"),
    TRACK("track"),
    TRAILER("trailer"),
    TVSHOWID("tvshowid"),
    UNIQUEID("uniqueid"),
    USERRATING("userrating"),
    VOTES("votes"),
    WATCHEDEPISODES("watchedepisodes"),
    WRITER("writer"),
    YEAR("year");

    override fun toString(): String {
        return fieldName
    }

    companion object {
        @JvmStatic
        fun getAllFields(): List<ListFieldsAll> {
            return ListFieldsAll.values().asList()
        }
    }
}